name: CI - Catalog Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/catalog/**'
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1
  ENVIRONMENT: dev
  CONTEXT_PATH: ./src/catalog
  IMAGE_NAME: devsecops-dev-catalog # <--- Đổi thành biến định nghĩa tên Image cục bộ
  SONAR_PROJECT_KEY: devsecops-retail-store-catalog
  SONAR_ORGANIZATION: huycon2352code

jobs:
  build-secure-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---- 1. TỐI ƯU CACHE CHO MAVEN DEPENDENCIES ----
      - name: Set up JDK 21 với Cache của Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Compile Java Code
        run: |
          cd ${{ env.CONTEXT_PATH }}
          chmod +x mvnw
          ./mvnw compile -DskipTests
          
      # -------------------------------------------------------------
      # 2. QUÉT MÃ NGUỒN (SAST) VỚI SONARQUBE CLOUD
      # -------------------------------------------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.projectBaseDir=${{ env.CONTEXT_PATH }}
            -Dsonar.sources=.
            -Dsonar.java.binaries=target/classes
            -X

      # ---- 3. TỐI ƯU CACHE CHO DOCKER LAYERS (BUILDKIT) ----
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -------------------------------------------------------------
      # 4. BUILD DOCKER IMAGE (CHỈ LƯU LOCAL RUNNER)
      # -------------------------------------------------------------
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_PATH }}
          # Thay đổi cấu trúc tag ở đây, không dùng biến ecr outputs nữa
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          push: false 
          load: true  # Vẫn giữ load=true để đẩy image vào Docker daemon của Runner
          cache-from: type=gha 
          cache-to: type=gha,mode=max 

      # -------------------------------------------------------------
      # 5. QUÉT BẢO MẬT DOCKER IMAGE (TRIVY IMAGE)
      # -------------------------------------------------------------
      - name: Run Trivy vulnerability scanner on Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '0' 
          severity: 'CRITICAL,HIGH'