name: CI - UI Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/ui/**' # Chỉ chạy khi có thay đổi trong thư mục UI
  workflow_dispatch: # Giữ lại nút bấm tay nếu cần

env:
  AWS_REGION: ap-southeast-1
  ENVIRONMENT: dev
  CONTEXT_PATH: ./src/ui
  ECR_REPO: devsecops-dev-ui
  SONAR_PROJECT_KEY: devsecops-retail-store-ui # Key bạn đặt trên Sonar Cloud
  SONAR_ORGANIZATION: huycon2352code       # Tên Organization trên Sonar Cloud

jobs:
  build-secure-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # SonarQube cần fetch-depth: 0 để phân tích lịch sử git chính xác

      # -------------------------------------------------------------
      # 1. QUÉT MÃ NGUỒN (SAST) VỚI SONARQUBE CLOUD (ACTION MỚI)
      # -------------------------------------------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_URL }} # Đảm bảo bạn đã khai báo Repository Variable mang tên SONAR_URL (giá trị: https://sonarcloud.io)
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.projectBaseDir=${{ env.CONTEXT_PATH }}
            -Dsonar.sources=.
            -X

      # -------------------------------------------------------------
      # 2. QUÉT BẢO MẬT THƯ MỤC FILE (TRIVY FS)
      # -------------------------------------------------------------
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: ${{ env.CONTEXT_PATH }}
          format: 'table'
          exit-code: '1' # Đổi thành 1 để chặn pipeline nếu phát hiện lỗi nặng
          severity: 'CRITICAL,HIGH'

      # -------------------------------------------------------------
      # 3. BUILD DOCKER IMAGE
      # -------------------------------------------------------------
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPO }}:$IMAGE_TAG ${{ env.CONTEXT_PATH }}

      # -------------------------------------------------------------
      # 4. QUÉT BẢO MẬT DOCKER IMAGE (TRIVY IMAGE)
      # -------------------------------------------------------------
      - name: Run Trivy vulnerability scanner on Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # Đổi thành 1 để chặn không cho push nếu image dính lỗi
          severity: 'CRITICAL,HIGH'

