name: Test GitOps Update Only (No Build)

on:
  # Cho phép bạn bấm nút chạy bằng tay trên giao diện GitHub Actions
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Tên service muốn test (vd: ui, catalog, orders, cart, checkout)'
        required: true
        default: 'orders'
        type: choice
        options:
          - ui
          - catalog
          - checkout
          - cart
          - orders
      test_tag:
        description: 'Image Tag giả lập để test (vd: test-123 hoặc commit SHA)'
        required: true
        default: 'test-tag-123'

env:
  AWS_ECR_REGISTRY: ${{ vars.AWS_ECR_REGISTRY }}
  GITOPS_REPO: ${{ vars.GITOPS_REPO }}

jobs:
  test-deploy:
    runs-on: ubuntu-latest

    steps:
      # ==========================================================
      # INSTALL KUSTOMIZE
      # ==========================================================
      # Cài đặt kustomize mất tầm 2-3 giây
      - name: Install Kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

      # ==========================================================
      # UPDATE GITOPS REPO (Bê nguyên logic cũ qua)
      # ==========================================================
      - name: Update GitOps Manifest
        run: |
          git clone https://${{ secrets.GITOPS_TOKEN }}@github.com/${{ env.GITOPS_REPO }}.git gitops

          cd gitops/k8s/overlays/dev

          echo "Đang update $SERVICE_NAME -> $MOCK_TAG"

          kustomize edit set image \
            $SERVICE_NAME=248195880649.dkr.ecr.ap-southeast-1.amazonaws.com/$SERVICE_NAME:$MOCK_TAG

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add kustomization.yaml

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "test update $SERVICE_NAME -> $MOCK_TAG"

          git pull --rebase origin main
          git push origin main